In [146]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
from bs4 import BeautifulSoup
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait as W
from selenium.webdriver.support import expected_conditions as EC
import time
from selenium.webdriver.common.keys import Keys
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed
import requests
import json
from wakepy import keepawake
from selenium.webdriver.chrome.options import Options
import logging
import re
import os
from selenium.webdriver.common import service
from selenium.webdriver.remote.remote_connection import LOGGER
from urllib3.connectionpool import log as urllibLogger
import logging
import undetected_chromedriver as uc

In [29]:
options = Options()
# options.add_argument('--disable-gpu')
# options.add_argument("--headless")
options.add_argument("--log-level=3")
# options.add_argument('--blink-settings=imagesEnabled=false')
# options.binary_location =r'C:\Users\akash\Desktop\LindIn\driver\chrome.exe'
options.binary_location =r'driver\chrome.exe'

# options.add_argument("--no-sandbox")
driver = webdriver.Chrome(service=Service(executable_path='chromedriver.exe'), options=options)

In [42]:
page = driver.page_source
soup = BeautifulSoup(page, 'html.parser')

In [234]:
linkdin_Data = {'position':[],'company_name':[],'location':[],'hr_name':[],'hr_position':[],'hr_link':[],'email':[],'phone':[]}

In [249]:
data = driver.find_elements(By.CLASS_NAME,'scaffold-layout__list-item')

In [250]:

for i in data:
    i.click()
    time.sleep(5)
    data_position = i.text.split('\n')
    linkdin_Data['position'].append(data_position[0])
    linkdin_Data['company_name'].append(data_position[1])
    linkdin_Data['location'].append(data_position[2])
    try:
        hr = driver.find_element(By.CLASS_NAME,'hirer-card__container').text
        hr_ = hr.split('\n')
        linkdin_Data['hr_name'].append(hr_[0])
        linkdin_Data['hr_position'].append(hr_[2])
        hr_link = driver.find_element(By.CLASS_NAME,'hirer-card__hirer-information').find_element(By.CLASS_NAME,'app-aware-link ').get_attribute('href')        
        linkdin_Data['hr_link'].append(hr_link)
    except:
        linkdin_Data['hr_name'].append('nan')
        linkdin_Data['hr_position'].append('nan')
        linkdin_Data['hr_link'].append('nan')
        
    text= driver.find_element(By.CLASS_NAME,'jobs-description-content__text--stretch').text
    try:
        indian_phone_pattern = r'(\+91|91|0)?\s?[6-9]\d{9}'
        indian_phone_numbers = re.search(indian_phone_pattern, text)
        number = indian_phone_numbers.group()
        linkdin_Data['phone'].append(number)
    except:
        linkdin_Data['phone'].append('nan')
        
        
    try:
        email_pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b'
        email_addresses = re.findall(email_pattern, text)
        linkdin_Data['email'].append(email_addresses[0])
    except:
        linkdin_Data['email'].append('nan')

In [251]:
import pandas as pd

In [252]:
df = pd.DataFrame(linkdin_Data)

In [253]:
df

,position,company_name,location,hr_name,hr_position,hr_link,email,phone
0,Node.js / Python Developer,Jiitak Inc.,"Kochi, Kerala, India (On-site)",Martin Noel,Co-Founder @ 株式会社JIITAK | New Business Develop...,https://www.linkedin.com/in/martin-noel-ba6a36183,nan,nan
1,Python Developer,A3logics,"Jaipur, Rajasthan, India (On-site)",Heena Dua,Senior Human Resources Executive at A3Logics,https://www.linkedin.com/in/heenadua,nan,nan
2,Junior Qliksense Developer,Aray Consulting LLP,"Pune, Maharashtra, India (Hybrid)",Yatindra Jha,Spreading Knowledge on Robotic Process Automation,https://www.linkedin.com/in/yatindrajha,hiring@araycon.com,nan
3,"Junior Application Developer (Java, Cloud)",Equifax,"Trivandrum, Kerala, India",nan,nan,nan,nan,nan
4,Junior Java Developer,Hitachi Energy,"Bengaluru, Karnataka, India (Hybrid)",nan,nan,nan,nan,nan
...,...,...,...,...,...,...,...,...
95,junior dotnet developer,Colan Infotech Private Limited,"Chennai, Tamil Nadu, India (Hybrid)",nan,nan,nan,nan,nan
96,Junior Java Developer,CKS SOLUTIONS,"Agasthiswaram, Tamil Nadu, India (On-site)",nan,nan,nan,nan,nan
97,Junior Java Developer,TandA HR Solutions,"Sahibzada Ajit Singh Nagar, Punjab, India",nan,nan,nan,nan,nan
98,Junior Java Developer,NIBODHAH,"Gandhinagar, Gujarat, India (On-site)",nan,nan,nan,nan,nan
99,Junior SQL Developer,D Recruitment Company,"Bengaluru, Karnataka, India (On-site)",nan,nan,nan,nan,nan

In [254]:
df.to_excel('linkdin.xlsx',index=False)